### ISSUE TITLE
Favicon is broken

### ISSUE THREAD

**Issue by BizzarBlitz** [DiscordLuau/docs#1]
Title is self-explanatory. When using inspect element and going to https://discord-luau-docs.deno.dev/src/assets/favicon.png you get a 508 error (loop detected) which may be the cause?

![image](https://github.com/user-attachments/assets/9c99c179-ff8d-4f82-87e6-e71c5053e88d)

Browser is Opera GX (Chromium)

**Comment by BizzarBlitz** [comment]
Ok after googling it it turns out it's because this says `"shortcut-icon"` instead of just `"icon"`
![image](https://github.com/user-attachments/assets/76c1b6dc-d21e-4a94-9d11-17a5be35c468)

**Comment by CompeyDev** [comment]
> Ok after googling it it turns out it's because this says "shortcut-icon" instead of just "icon"

This is incorrect. The favicon is injected using a FaviconLoader.mjs file if I'm not wrong. Monitoring network logs reveal that the requests for the favicon return a 404. Will investigate more.
